### ISSUE TITLE
charmstore truncates the bundle.yaml file in the archive

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore#174] opened 2014-10-22 15:40 UTC
Looking at 

http://juju.mycomiclife.net/cs/v4/mongodb-cluster/archive/bundle.yaml

the top section of the bundles.yaml which houses the name of the bundle is truncated.

The original is at
http://bazaar.launchpad.net/~charmers/charms/bundles/mongodb-cluster/bundle/view/head:/bundles.yaml

The archive includes a .orig, but this means that grabbing the bundles.yaml from the api is not close enough to tell where it came from, what the bundle name is, etc. We should keep that first section.

**Comment by urosj** [comment] 2014-10-23 05:37
I can't reproduce the error. Please confirm that it is still valid.

**Comment by mitechie** [comment] 2014-10-23 17:20
so the first line of the original bundle file is:

```
mongodb-cluster: 
```

And the first line of the bundle.yaml from the api is

```
services:
```

This is what I'm wondering about.

**Comment by rogpeppe** [comment] 2014-10-24 07:35
This is by design. The new bundle format only contains a single bundle, so
there is no top level needed to hold the names of several bundle.
The name of the bundle is what you use to name it.

It is possible that we might add an informational name attribute at the top level,
but based on discussion online, this may be problematic.

The suggested solution to this is to add another /meta endpoint
which returns the name of the entity, rather than adding the
(potentially misleading) name to the bundle metadata.

**Comment by urosj** [comment] 2014-10-27 08:30
The /meta endpoint does not help here. When a bundle is downloaded, the information about an owner and name is lost. We might need write this info into bundle.yaml based on a URL of a bundle.

Linked to isse #170 .

**Comment by rogpeppe** [comment] 2014-10-28 12:36
When you download a bundle, you must already have the
owner and name available, as you need them to download it.

**Comment by mitechie** [comment] 2014-10-28 12:40
But when you come back to that a month later can you tell where it came
from?

**Comment by rogpeppe** [comment] 2014-10-28 13:23
It depends where you stored it. Hopefully you stored it under the
name that you used to retrieve it. The name of a thing does not have to be
within the contents of that thing - we don't put the name of a file inside
every file in a file store, for example. If we did, it would be a recipe
for confusion, as the name inside the file contents would not necessarily
match the name that you used to access the file. That's the core
of the issue here.

Note that I'm not at all opposed to having an _presentation-only_
name inside charm or bundle metadata, as that doesn't pose the
same problems.

**Comment by urosj** [comment] 2014-11-18 19:53
We moved this to another issue. Closing this.

**Closed as completed by urosj** 2014-11-18 19:53 UTC
