### ISSUE TITLE
Header size exceeded by authn and authz /charmstore/ macaroons

### ISSUE THREAD

**Issue by cmars** [juju/charmstore#618] opened 2016-05-18 16:28 UTC
I'm now hitting the header size limit when deploying a private charm with terms. `juju deploy` command errors intermittently now with:

```
ERROR storing charm for URL "cs:~redacted/private-charm-6": cannot unmarshal error response "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD H
TML 2.0//EN\">\n<html><head>\n<title>400 Bad Request</title>\n</head><body>\n<h1>Bad Request</h1>\n<p>Your browser sent a re
quest that this server could not understand.<br />\nSize of a request header field exceeds server limit.<br />\n<pre>\nCooki
e\n</pre>\n</p>\n<hr>\n<address>Apache/2.4.7 (Ubuntu) Server at api.jujucharms.com Port 443</address>\n</body></html>\n": in
valid character '<' looking for beginning of value
```

I believe this may be caused by having 2 /charmstore/ cookies, an "authz" and an "authn", each with third-party caveats:

```
    {
        "CanonicalHost": "api.jujucharms.com",
        "Creation": "2016-05-18T09:01:34.882273747-07:00",
        "Domain": "api.jujucharms.com",
        "Expires": "2016-05-19T16:01:32.097453008Z",
        "HostOnly": true,
        "HttpOnly": false,
        "LastAccess": "2016-05-18T09:14:48.495307391-07:00",
        "Name": "macaroon-authn",
        "Path": "/charmstore/",
        "Persistent": true,
        "Secure": false,
        "Updated": "2016-05-18T09:01:34.882273747-07:00",
        "Value": [
            {
                "caveats": [
                    {
                        "cid": "scrubbed",
                        "cl": "https://api.jujucharms.com/identity/v1/discharger",
                        "vid": "scrubbed"
                    },
                    {
                        "cid": "allow read-no-terms write"
                    },
                    {
                        "cid": "time-before 2016-05-19T16:01:32.097453008Z"
                    }
                ],
                "identifier": "scrubbed",
                "location": "charmstore",
                "signature": "scrubbed"
            },
            {
                "caveats": [
                    {
                        "cid": "declared uuid 28c261c4-8fe0-5fba-bf1f-eda1b6e889b8"
                    },
                    {
                        "cid": "declared username cmars"
                    },
                    {
                        "cid": "time-before 2016-05-19T16:01:34.855862805Z"
                    }
                ],
                "identifier": "scrubbed",
                "location": "",
                "signature": "scrubbed"
            }
        ]
    },
    {
        "CanonicalHost": "api.jujucharms.com",
        "Creation": "2016-05-18T09:01:42.990086151-07:00",
        "Domain": "api.jujucharms.com",
        "Expires": "2016-05-18T16:15:46.116084956Z",
        "HostOnly": true,
        "HttpOnly": false,
        "LastAccess": "2016-05-18T09:14:48.495307391-07:00",
        "Name": "macaroon-authz",
        "Path": "/charmstore/",
        "Persistent": true,
        "Secure": false,
        "Updated": "2016-05-18T09:14:48.495234591-07:00",
        "Value": [
            {
                "caveats": [
                    {
                        "cid": "scrubbed",
                        "cl": "https://api.jujucharms.com/identity/v1/discharger",
                        "vid": "scrubbed"
                    },
                    {
                        "cid": "allow read-with-terms read-no-terms"
                    },
                    {
                        "cid": "time-before 2016-05-18T16:15:46.116084956Z"
                    },
                    {
                        "cid": "is-entity cs:~redacted/private-charm-6"
                    },
                    {
                        "cid": "scrubbed",
                        "cl": "https://api.jujucharms.com/terms",
                        "vid": "scrubbed"
                    }
                ],
                "identifier": "scrubbed",
                "location": "charmstore",
                "signature": "scrubbed"
            },
            {
                "caveats": [
                    {
                        "cid": "declared uuid 28c261c4-8fe0-5fba-bf1f-eda1b6e889b8"
                    },
                    {
                        "cid": "declared username cmars"
                    },
                    {
                        "cid": "time-before 2016-05-19T16:14:47.327115421Z"
                    }
                ],
                "identifier": "scrubbed",
                "location": "",
                "signature": "scrubbed"
            },
            {
                "caveats": [],
                "identifier": "scrubbed",
                "location": "",
                "signature": "scrubbed"
            }
        ]
    },
```

Here's a private paste of the full go-cookies dump, in case that helps: https://pastebin.canonical.com/156746/

**Comment by tvansteenburgh** [comment] 2016-11-03 21:35
``` bash
tvansteenburgh@xenial-vm:~/src/review-queue⟫ juju agree -B --yes ibm-http-server/2 ibm-http-plg/1 ibm-http-wct/1
Agreed to revision 2 of ibm-http-server for Juju users
Agreed to revision 1 of ibm-http-plg for Juju users
Agreed to revision 1 of ibm-http-wct for Juju users
tvansteenburgh@xenial-vm:~/src/review-queue⟫ charm pull ~ibmcharmers/trusty/ibm-http-5 /tmp/39
ERROR cannot get archive: cannot unmarshal error response "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>400 Bad Request</title>\n</head><body>\n<h1>Bad Request</h1>\n<p>Your browser sent a request that this server could not understand.<br />\nSize of a request header field exceeds server limit.<br />\n<pre>\nCookie\n</pre>\n</p>\n<hr>\n<address>Apache/2.4.7 (Ubuntu) Server at api.jujucharms.com Port 443</address>\n</body></html>\n": invalid character '<' looking for beginning of value
```

**Comment by bac** [comment] 2016-11-03 22:42
Hi @tvansteenburgh which charm are you using?  The one from /usr/bin/charm or /snap version?

I ran into this problem yesterday when using /usr/bin/charm.  @rogpeppe suggested I build my own from source and then `charm pull` worked. I then tried the snap version and it worked too.  And continuing to experiment I tried the /usr/bin/charm version and at that point it succeeded.

So, it seem like one of the various versions may have re-written my `$HOME/.go-cookies` file allowing various versions to work.

Sorry for the inconvenience but additional feedback would be helpful.

**Comment by tvansteenburgh** [comment] 2016-11-03 22:44
Hey @bac, this is with /usr/bin/charm. Incidentally, after this error, I ran the same `charm pull` command again and it worked.

**Comment by jamesbeedy** [comment] 2016-11-04 00:48
@bac, @tvansteenburgh I hit this all the time. I've gone through all the troubleshooting steps to no avail or resolve 😤

**Comment by jamesbeedy** [comment] 2016-11-04 00:50
@cmars, @frankban, @mitechie ^

**Comment by bac** [comment] 2016-11-04 13:14
Hi, the short-term plan is for us to increase the header-size which may provide relief while we look for a proper solution.

In the interim, retrying, attempting to use the charm installed from the snap, and removing $HOME/.go-cookies have been seen to work but not all of the time.

**Comment by bac** [comment] 2016-11-04 19:47
The apache config change has been made on staging and afterwards I cannot reproduce the problem. Hopefully that fixes it for now.

Plan to release to production on Monday.

**Comment by johnsca** [comment] 2016-11-08 17:31
@bac Has the fix for this been done in production?

**Comment by bac** [comment] 2016-11-08 18:49
@johnsca It was applied yesterday.  Please let me know if you see it again.

**Closed as completed** 2018-07-11 12:47 UTC
Labels: bug, fix-released
