### ISSUE TITLE
Icon endpoint not returning default icon for existing charm

### ISSUE THREAD

**Issue by hatched** [juju/charmstore#222] opened 2014-11-17 20:24 UTC
https://api.jujucharms.com/v4/~cf-charmers/trusty/collector-v1-0/icon.svg returns 404 instead of the default icon

https://api.jujucharms.com/v4/~cf-charmers/trusty/collector-v1-0 (not found)
https://api.jujucharms.com/v4/~cf-charmers/trusty/collector-v1-0/meta/any (id found)
https://api.jujucharms.com/v4/~cf-charmers/trusty/collector-v1-0/meta/any?include=manifest (none matching)

**Comment by mitechie** [comment] 2014-11-17 20:33
This seems more like the data is in mongodb but not in the storage side?

**Comment by hatched** [comment] 2014-11-17 20:44
Here is another example where the entity is not found but the ID is: https://api.jujucharms.com/v4/trusty/elasticsearch-3/icon.svg

**Comment by frankban** [comment] 2014-11-17 20:59
It seems to me that the icon endpoint is correct: those charms are not in the store.
The problem is probably in the meta/any endpoint, which just returns the given id if it is fully qualified, e.g.:
https://api.jujucharms.com/v4/trusty/no-such-charm-or-bundle-42/meta/any

If we actually check the elasticsearch revisions we only get revisions 7 and 8:
https://api.jujucharms.com/v4/trusty/elasticsearch/meta/revision-info

So https://api.jujucharms.com/v4/trusty/elasticsearch/icon.svg correctly returns the icon; the same for https://api.jujucharms.com/v4/trusty/elasticsearch-8/icon.svg

We should either 1) fix the meta/any endpoint or 2) just remove the id from there and start using the meta/id\* endpoints. I'd suggest option 2.

**Comment by urosj** [comment] 2014-11-17 21:19
I'd go with meta/id endpoints as suggested by Francesco. But we need to
have a look if it's really just meta/any bug or something to do with
blobstore.

**Comment by hatched** [comment] 2014-11-17 22:49
I have come across even more of these which I am just putting here in hopes that it helps with a solution

https://api.jujucharms.com/v4/~paulgear/precise/quassel-core-2/icon.svg
https://api.jujucharms.com/v4/~adam-collard/trusty/unmanaged-installer-testing-2/icon.svg
https://api.jujucharms.com/v4/oneiric/mongodb-1/icon.svg 
https://api.jujucharms.com/v4/~charmers/oneiric/cf-mongodb-0/icon.svg
https://api.jujucharms.com/v4/oneiric/node-app-0/icon.svg

**Comment by urosj** [comment] 2014-11-18 14:52
There is a bug in /meta/any and will be fixed. 

@hatched How did you come up with those charm urls anyway? As I can't "search" them at all.

**Comment by urosj** [comment] 2014-11-18 19:18
This seems related to the ingestion bug and not to the icon endpoint. The icon endpoint works ok on the charms that exist. It's just a case that the charms listed here do not exist.

**Comment by urosj** [comment] 2014-11-18 19:25
Changed this issue to #224

**Closed as completed by urosj** 2014-11-18 19:25 UTC
