### ISSUE TITLE
charm icons in bundle preview are incorrectly masked with Firefox

### ISSUE THREAD

**Issue by nobuto-m** [juju/charmstore#524] opened 2016-02-01 17:50 UTC
For example when opening https://jujucharms.com/openstack-base/bundle/ with Firefox 44 on Ubuntu Desktop, the charm icons are incorrectly masked. See the image below.

![bundle-preview](https://cloud.githubusercontent.com/assets/4356209/12725703/4ce8bf58-c957-11e5-9f13-db284b5169b0.png)

**Comment by urosj** [comment] 2016-02-04 21:59
Hi, @nobuto-m 

Thanks for the feedback, I can confirm the issue on FF (41.x and 44.x). The team will look into it.

**Comment by sparkiegeek** [comment] 2016-02-05 09:03
Duplicate of https://github.com/CanonicalLtd/jujucharms.com/issues/206 ?

**Comment by makyo** [comment] 2016-02-08 14:42
@sparkiegeek yes; this issue should be used for the fact that charmstore will need to update dependencies.tsv, at which point CanonicalLtd/jujucharms.com#206 will be marked fix-committed, then fix-released when we update jujucharms.com

**Closed as completed** 2016-02-09 09:54 UTC
