### ISSUE TITLE
api search with owner returns no results

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore#232] opened 2014-11-25 07:13 UTC
In new production with new ingestion the /solutions page failed to load content due to the owner= on the api request. 

After a fresh ingestion any owner on the api will fail to return results. 

https://api.jujucharms.com/v4/search?series=trusty&owner=&limit=600

Failed to return any results.

**Comment by urosj** [comment] 2014-11-25 09:39
I could not reproduce this with CS 4.0.1, either from charm deploys (with juju set source from ppa - stable) to directly running from code. Checked ES and it has proper mapping. Asked IS to get ES mappings, but noone was available anymore.

Search works with owner= (empty) or set to some value. 

The only logical reason that it did not work could be that old ES mapping was used which lacks denormalised URL values like name, series and user (and therefore fails to set filter on them). Search would work due to different fields being used (known from old mapping schema).

**Comment by urosj** [comment] 2014-11-26 00:47
Fixed now. Problem was in wrong mappings.

**Closed as completed by urosj** 2014-11-26 00:47 UTC
